In [2]:
import os
import pandas as pd

In [5]:


# Specify the source folder and the destination folder
#source_folder = '..\\data\\raw\\data-vn-20230228\\data-vn-20230228\\stock-historical-data'  # Replace with your folder path
#destination_file = '..\\data\\toprocess\\combined_all_close.csv'  # Path for saving the combined file

source_folder = '..\\data\\raw\\data-vn-20230228\\data-vn-20230228\\stock-historical-data'
destination_file = '..\\data\\toprocess\\close_price_vn_data.csv'
# Function to extract the last 7 days of closing prices and return a DataFrame with ticker name as the column
def extract_close_columns(file_path):
    try:
        # Read the CSV file into a DataFrame
        df = pd.read_csv(file_path)

        # Ensure 'TradingDate' column is in dateTradingDate format (adjust column name if necessary)
        df['TradingDate'] = pd.to_datetime(df['TradingDate'], errors='coerce')

        # Sort by TradingDate in ascending order
        df = df.sort_values(by='TradingDate', ascending=True)

        # Drop rows with missing 'Close' or 'TradingDate' values
        df.dropna(subset=['Close', 'TradingDate'], inplace=True)

        # Extract the 'Close' column and keep the 'TradingDate'
        close_col = df[['TradingDate', 'Close']]

        return close_col
    except Exception as e:
        print(f"Error processing file {file_path}: {e}")
        return None

# Initialize an empty DataFrame to combine the Close prices
combined_df = pd.DataFrame()

# Loop through all files in the source folder
for filename in os.listdir(source_folder):
    file_path = os.path.join(source_folder, filename)

    # Check if it's a file (not a directory)
    if os.path.isfile(file_path):
        # Extract the last 7 days of data for the file
        close_data = extract_close_columns(file_path)
        
        if close_data is not None:
            # Get the ticker (file name without the extension)
            ticker = filename.split('-')[0]

            # Rename the 'Close' column to the ticker
            close_data.rename(columns={'Close': ticker}, inplace=True)

            # Merge the data with the combined dataframe
            if combined_df.empty:
                # If the combined dataframe is empty, initialize it with the first file's data
                combined_df = close_data
            else:
                # Otherwise, merge on the 'TradingDate' column
                combined_df = pd.merge(combined_df, close_data, on='TradingDate', how='inner')

# Save the combined DataFrame to a CSV file
combined_df.to_csv(destination_file, index=False)

print(f"Combined data saved to {destination_file}")

Combined data saved to ..\data\toprocess\close_price_vn_data.csv

In [4]:
data = pd.read_csv("..\\data\\toprocess\\combined_all_close.csv")
data.head(10)

,TradingDate,SZL,TA3,TA6,TA9,TAN,TAR,TAW,TB8,TBC,...,XHC,XLV,XMC,XMD,XMP,XPH,YBC,YBM,YEG,YTC
0,2023-01-06,47000.0,5700.0,13900.0,12600.0,55100.0,11600.0,19900.0,9100.0,30600.0,...,34000.0,7600.0,7200.0,6300.0,18900.0,8800.0,3800.0,5780.0,8890.0,110000.0
1,2023-01-09,48000.0,5700.0,13900.0,12700.0,55100.0,11900.0,19900.0,9100.0,30400.0,...,31000.0,7600.0,6900.0,6500.0,18900.0,8800.0,3800.0,5780.0,8720.0,110000.0
2,2023-01-10,48000.0,5700.0,13900.0,12700.0,55100.0,11800.0,19900.0,9100.0,30300.0,...,31000.0,7600.0,7100.0,7300.0,18900.0,8800.0,3800.0,5710.0,8620.0,110000.0
3,2023-01-11,46000.0,5700.0,13900.0,12700.0,55100.0,12100.0,19900.0,9100.0,30300.0,...,31000.0,7600.0,6900.0,7300.0,18900.0,8800.0,3800.0,5720.0,8600.0,110000.0
4,2023-01-12,46000.0,5700.0,13900.0,12700.0,55100.0,12300.0,19900.0,9100.0,30200.0,...,31000.0,7600.0,6800.0,6400.0,18000.0,8800.0,3800.0,5690.0,8700.0,110000.0
5,2023-01-13,46000.0,5700.0,13900.0,13800.0,55100.0,12000.0,19900.0,9100.0,30300.0,...,31000.0,7600.0,6900.0,6500.0,18000.0,7500.0,4300.0,5500.0,8640.0,110000.0
6,2023-01-16,43800.0,5700.0,13900.0,13800.0,55100.0,12000.0,19900.0,9100.0,30400.0,...,31000.0,7600.0,7100.0,6000.0,18000.0,7500.0,4300.0,5500.0,8440.0,110000.0
7,2023-01-17,46850.0,5700.0,13900.0,13800.0,55100.0,12300.0,19900.0,9100.0,30450.0,...,31000.0,7600.0,7100.0,6600.0,17100.0,7500.0,4900.0,5500.0,8630.0,110000.0
8,2023-01-18,46000.0,5700.0,13900.0,13800.0,55100.0,12600.0,19900.0,9100.0,30550.0,...,31000.0,7600.0,7100.0,6800.0,17100.0,7500.0,5600.0,5640.0,8830.0,110000.0
9,2023-01-19,46000.0,5700.0,13900.0,13800.0,55100.0,12500.0,19900.0,9100.0,30600.0,...,31000.0,7600.0,7100.0,6600.0,17100.0,7500.0,6400.0,5600.0,9090.0,110000.0

In [7]:
close_data = pd.read_csv(destination_file)
close_data.head(10)

,TradingDate,SZL,TA3,TA6,TA9,TAN,TAR,TAW,TB8,TBC,...,XHC,XLV,XMC,XMD,XMP,XPH,YBC,YBM,YEG,YTC
0,2023-01-06,47000.0,5700.0,13900.0,12600.0,55100.0,11600.0,19900.0,9100.0,30600.0,...,34000.0,7600.0,7200.0,6300.0,18900.0,8800.0,3800.0,5780.0,8890.0,110000.0
1,2023-01-09,48000.0,5700.0,13900.0,12700.0,55100.0,11900.0,19900.0,9100.0,30400.0,...,31000.0,7600.0,6900.0,6500.0,18900.0,8800.0,3800.0,5780.0,8720.0,110000.0
2,2023-01-10,48000.0,5700.0,13900.0,12700.0,55100.0,11800.0,19900.0,9100.0,30300.0,...,31000.0,7600.0,7100.0,7300.0,18900.0,8800.0,3800.0,5710.0,8620.0,110000.0
3,2023-01-11,46000.0,5700.0,13900.0,12700.0,55100.0,12100.0,19900.0,9100.0,30300.0,...,31000.0,7600.0,6900.0,7300.0,18900.0,8800.0,3800.0,5720.0,8600.0,110000.0
4,2023-01-12,46000.0,5700.0,13900.0,12700.0,55100.0,12300.0,19900.0,9100.0,30200.0,...,31000.0,7600.0,6800.0,6400.0,18000.0,8800.0,3800.0,5690.0,8700.0,110000.0
5,2023-01-13,46000.0,5700.0,13900.0,13800.0,55100.0,12000.0,19900.0,9100.0,30300.0,...,31000.0,7600.0,6900.0,6500.0,18000.0,7500.0,4300.0,5500.0,8640.0,110000.0
6,2023-01-16,43800.0,5700.0,13900.0,13800.0,55100.0,12000.0,19900.0,9100.0,30400.0,...,31000.0,7600.0,7100.0,6000.0,18000.0,7500.0,4300.0,5500.0,8440.0,110000.0
7,2023-01-17,46850.0,5700.0,13900.0,13800.0,55100.0,12300.0,19900.0,9100.0,30450.0,...,31000.0,7600.0,7100.0,6600.0,17100.0,7500.0,4900.0,5500.0,8630.0,110000.0
8,2023-01-18,46000.0,5700.0,13900.0,13800.0,55100.0,12600.0,19900.0,9100.0,30550.0,...,31000.0,7600.0,7100.0,6800.0,17100.0,7500.0,5600.0,5640.0,8830.0,110000.0
9,2023-01-19,46000.0,5700.0,13900.0,13800.0,55100.0,12500.0,19900.0,9100.0,30600.0,...,31000.0,7600.0,7100.0,6600.0,17100.0,7500.0,6400.0,5600.0,9090.0,110000.0